apiVersion: v1
kind: Service
metadata:
  name: {{ include "transporter-cp.fullname" . }}
  labels:
    {{- include "transporter-cp.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.websocketPort }}
      targetPort: websocket
      protocol: TCP
      name: websocket
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "transporter-cp.selectorLabels" . | nindent 4 }}
