{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "transporter-cp.serviceAccountName" . }}
  labels:
    {{- include "transporter-cp.labels" . | nindent 4 }}
{{- end }}
