kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cp-cluster
nodes:
  - role: control-plane
    extraPortMappings:
      # Map NodePort 30080 (CP WebSocket) to localhost:30080
      - containerPort: 30080
        hostPort: 30080
        protocol: TCP
      # Map NodePort 30090 (Memphis UI) to localhost:30090
      - containerPort: 30090
        hostPort: 30090
        protocol: TCP
      # Map NodePort 30666 (Memphis broker) to localhost:30666
      - containerPort: 30666
        hostPort: 30666
        protocol: TCP
